name: Spell check
on:
  push:
    paths:
      - src/**
      - docs/**
      - zensical.toml

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.18.0'
      - name: Run spell check
        run: make spell-check